version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: qp-assessment
    ports:
      - "5431:5432"   # Host port 5431 maps to container port 5432

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db            # Use the service name, not localhost
      DB_PORT: 5432          # Connect using the internal port of the db container
      DB_USERNAME: postgres
      DB_PASSWORD: '1234'
      DB_NAME: qp-assessment